//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptsDictionaryMeaning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConceptsDictionaryMeaning()
        {
            this.ConceptsDictionaryMeaningsToGroups = new HashSet<ConceptsDictionaryMeaningsToGroup>();
        }
    
        public int ID { get; set; }
        public int ConceptDictionaryID { get; set; }
        public string Meaning { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual ConceptsDictionary ConceptsDictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConceptsDictionaryMeaningsToGroup> ConceptsDictionaryMeaningsToGroups { get; set; }
    }
}
