//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptsDictionaryMeaningsToGroup
    {
        public int ID { get; set; }
        public int ConceptsDictionaryMeaningID { get; set; }
        public int GroupID { get; set; }
    
        public virtual ConceptsDictionaryMeaning ConceptsDictionaryMeaning { get; set; }
    }
}
