//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentGroup()
        {
            this.CommonExpressionsToGroups = new HashSet<CommonExpressionsToGroup>();
            this.MainContents = new HashSet<MainContent>();
            this.ContentPatternsToGroups = new HashSet<ContentPatternsToGroup>();
            this.ContentToAlternateGroups = new HashSet<ContentToAlternateGroup>();
            this.GroupsProperties = new HashSet<GroupsProperty>();
            this.RelationsSources = new HashSet<RelationsSource>();
        }
    
        public int GroupID { get; set; }
        public Nullable<int> GroupType { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> SequenceNumberByRootGroup { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public string XMLData { get; set; }
        public Nullable<int> RoutePriority { get; set; }
        public Nullable<int> NextGroupIDInLevel { get; set; }
        public Nullable<int> RootGroupID { get; set; }
        public string KeyWordIndex { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonExpressionsToGroup> CommonExpressionsToGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainContent> MainContents { get; set; }
        public virtual GroupsAndDividingType GroupsAndDividingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentPatternsToGroup> ContentPatternsToGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentToAlternateGroup> ContentToAlternateGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupsProperty> GroupsProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationsSource> RelationsSources { get; set; }
    }
}
