//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentOtherVersion
    {
        public int ID { get; set; }
        public long MainContentID { get; set; }
        public int VersionSourceID { get; set; }
        public string VersionOperation { get; set; }
        public int SequenceNumber { get; set; }
        public string Content { get; set; }
    
        public virtual MainContent MainContent { get; set; }
    }
}
