//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HebrewTextsEntities : DbContext
    {
        public HebrewTextsEntities()
            : base("name=HebrewTextsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContentGroup> ContentGroups { get; set; }
        public virtual DbSet<ContentOtherVersion> ContentOtherVersions { get; set; }
        public virtual DbSet<ContentToAlternateGroup> ContentToAlternateGroups { get; set; }
        public virtual DbSet<GroupsAndDividingType> GroupsAndDividingTypes { get; set; }
        public virtual DbSet<Letters_Ref> Letters_Ref { get; set; }
        public virtual DbSet<MainContent> MainContents { get; set; }
        public virtual DbSet<Niqqud_Ref> Niqqud_Ref { get; set; }
        public virtual DbSet<SetContentLog> SetContentLogs { get; set; }
        public virtual DbSet<TanakhCharacter> TanakhCharacters { get; set; }
        public virtual DbSet<TextVersionSource> TextVersionSources { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<DistinctWord> DistinctWords { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taamim_Ref> Taamim_Ref { get; set; }
        public virtual DbSet<Tanakh> Tanakhs { get; set; }
        public virtual DbSet<WordsInTanakh> WordsInTanakhs { get; set; }
        public virtual DbSet<RawImportStuff> RawImportStuffs { get; set; }
        public virtual DbSet<TalmudBavliRawImport> TalmudBavliRawImports { get; set; }
        public virtual DbSet<CommonExpression> CommonExpressions { get; set; }
        public virtual DbSet<CommonExpressionsToGroup> CommonExpressionsToGroups { get; set; }
        public virtual DbSet<ConceptsDictionary> ConceptsDictionaries { get; set; }
        public virtual DbSet<ConceptsDictionaryMeaning> ConceptsDictionaryMeanings { get; set; }
        public virtual DbSet<ConceptsDictionaryMeaningsToGroup> ConceptsDictionaryMeaningsToGroups { get; set; }
        public virtual DbSet<ContentPattern> ContentPatterns { get; set; }
        public virtual DbSet<ContentPatternsToGroup> ContentPatternsToGroups { get; set; }
        public virtual DbSet<ContentTypes_Ref> ContentTypes_Ref { get; set; }
        public virtual DbSet<RelationsBetweenCommonExpression> RelationsBetweenCommonExpressions { get; set; }
        public virtual DbSet<RelationTypesBetweenCommonExpressions_Ref> RelationTypesBetweenCommonExpressions_Ref { get; set; }
        public virtual DbSet<RootWordForm> RootWordForms { get; set; }
        public virtual DbSet<RootWord> RootWords { get; set; }
        public virtual DbSet<RootWordsToContent> RootWordsToContents { get; set; }
        public virtual DbSet<WordsDictionary> WordsDictionaries { get; set; }
        public virtual DbSet<WordsRelation> WordsRelations { get; set; }
        public virtual DbSet<Personality> Personalities { get; set; }
        public virtual DbSet<PersonalitiesInstancesInContent> PersonalitiesInstancesInContents { get; set; }
        public virtual DbSet<RelationsBetweenPersonality> RelationsBetweenPersonalities { get; set; }
        public virtual DbSet<RelationsSource> RelationsSources { get; set; }
        public virtual DbSet<RelationsBetweenGroup> RelationsBetweenGroups { get; set; }
        public virtual DbSet<GroupsProperty> GroupsProperties { get; set; }
        public virtual DbSet<TalmudBavliWord> TalmudBavliWords { get; set; }
        public virtual DbSet<MainContentWithGroupsLevel> MainContentWithGroupsLevels { get; set; }
    }
}
