//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainContent()
        {
            this.ContentOtherVersions = new HashSet<ContentOtherVersion>();
            this.ContentToAlternateGroups = new HashSet<ContentToAlternateGroup>();
            this.ContentToAlternateGroups1 = new HashSet<ContentToAlternateGroup>();
            this.RootWordsToContents = new HashSet<RootWordsToContent>();
            this.TanakhCharacters = new HashSet<TanakhCharacter>();
        }
    
        public long MainContentID { get; set; }
        public int GroupID { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<int> RootGroupID { get; set; }
        public Nullable<int> SequenceNumberByRootGroup { get; set; }
        public string Content { get; set; }
        public string LargeContent { get; set; }
        public Nullable<int> VersionSourceID { get; set; }
        public Nullable<int> NextContentID { get; set; }
        public string KeyWordIndex { get; set; }
    
        public virtual ContentGroup ContentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentOtherVersion> ContentOtherVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentToAlternateGroup> ContentToAlternateGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentToAlternateGroup> ContentToAlternateGroups1 { get; set; }
        public virtual TextVersionSource TextVersionSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootWordsToContent> RootWordsToContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TanakhCharacter> TanakhCharacters { get; set; }
    }
}
