//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainContentWithGroupsLevel
    {
        public long MainContentID { get; set; }
        public int GroupID { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<int> RootGroupID { get; set; }
        public Nullable<int> SequenceNumberByRootGroup { get; set; }
        public string Content { get; set; }
        public string LargeContent { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> NextContentID { get; set; }
        public string KeyWordIndex { get; set; }
        public Nullable<int> GroupTypeLevel1 { get; set; }
        public string GroupTypeNameLevel1 { get; set; }
        public Nullable<int> GroupSequenceLevel1 { get; set; }
        public string GroupKeyWordIndexLevel1 { get; set; }
        public string GroupNameLevel1 { get; set; }
        public Nullable<int> GroupIDLevel2 { get; set; }
        public Nullable<int> GroupTypeLevel2 { get; set; }
        public string GroupTypeNameLevel2 { get; set; }
        public Nullable<int> GroupSequenceLevel2 { get; set; }
        public string GroupKeyWordIndexLevel2 { get; set; }
        public string GroupNameLevel2 { get; set; }
        public Nullable<int> GroupIDLevel3 { get; set; }
        public Nullable<int> GroupTypeLevel3 { get; set; }
        public string GroupTypeNameLevel3 { get; set; }
        public Nullable<int> GroupSequenceLevel3 { get; set; }
        public string GroupKeyWordIndexLevel3 { get; set; }
        public string GroupNameLevel3 { get; set; }
        public Nullable<int> GroupIDLevel4 { get; set; }
        public Nullable<int> GroupTypeLevel4 { get; set; }
        public string GroupTypeNameLevel4 { get; set; }
        public Nullable<int> GroupSequenceLevel4 { get; set; }
        public string GroupKeyWordIndexLevel4 { get; set; }
        public string GroupNameLevel4 { get; set; }
        public Nullable<int> GroupIDLevel5 { get; set; }
        public Nullable<int> GroupTypeLevel5 { get; set; }
        public string GroupTypeNameLevel5 { get; set; }
        public Nullable<int> GroupSequenceLevel5 { get; set; }
        public string GroupKeyWordIndexLevel5 { get; set; }
        public string GroupNameLevel5 { get; set; }
        public Nullable<int> GroupIDLevel6 { get; set; }
        public Nullable<int> GroupTypeLevel6 { get; set; }
        public string GroupTypeNameLevel6 { get; set; }
        public Nullable<int> GroupSequenceLevel6 { get; set; }
        public string GroupKeyWordIndexLevel6 { get; set; }
        public string GroupNameLevel6 { get; set; }
    }
}
