//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalitiesInstancesInContent
    {
        public int InstanceID { get; set; }
        public int PersonalityID { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Personality Personality { get; set; }
    }
}
