//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personality()
        {
            this.PersonalitiesInstancesInContents = new HashSet<PersonalitiesInstancesInContent>();
            this.RelationsBetweenPersonalities = new HashSet<RelationsBetweenPersonality>();
            this.RelationsBetweenPersonalities1 = new HashSet<RelationsBetweenPersonality>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BornHebrewYear { get; set; }
        public Nullable<int> DeathHebrewYear { get; set; }
        public string LivingArea { get; set; }
        public string StudyPlace { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalitiesInstancesInContent> PersonalitiesInstancesInContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationsBetweenPersonality> RelationsBetweenPersonalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationsBetweenPersonality> RelationsBetweenPersonalities1 { get; set; }
    }
}
