//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawImportStuff
    {
        public int ID { get; set; }
        public Nullable<int> GroupSequenceLevel1 { get; set; }
        public Nullable<int> GroupSequenceLevel2 { get; set; }
        public Nullable<int> GroupSequenceLevel3 { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
    }
}
