//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationsBetweenCommonExpression
    {
        public int ID { get; set; }
        public int FromCommonExpressionID { get; set; }
        public int ToCommonExpressionID { get; set; }
        public int RelationType { get; set; }
        public string RelationDescription { get; set; }
    
        public virtual RelationTypesBetweenCommonExpressions_Ref RelationTypesBetweenCommonExpressions_Ref { get; set; }
    }
}
