//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationsBetweenGroup
    {
        public int ID { get; set; }
        public int FromGroupID { get; set; }
        public int ToGroupID { get; set; }
        public int RelationType { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string XMLData { get; set; }
    }
}
