//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetContentLog
    {
        public int ID { get; set; }
        public int GrpupID { get; set; }
        public string FullContent { get; set; }
        public string Status { get; set; }
        public System.DateTime AddedRecordDate { get; set; }
    }
}
