//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taamim_Ref
    {
        public int TaamID { get; set; }
        public string Taam { get; set; }
        public string TaamName { get; set; }
        public string Comments { get; set; }
    }
}
