//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalmudBavliWord
    {
        public string KeyWordIndex { get; set; }
        public string Word { get; set; }
        public Nullable<long> SequenceNumber { get; set; }
        public int RootGroupID { get; set; }
    }
}
