//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanakh
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int Chapter { get; set; }
        public int Verse { get; set; }
        public string Content { get; set; }
        public string NetContent { get; set; }
        public string TextOnly { get; set; }
        public Nullable<int> NewBookID { get; set; }
    }
}
