//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HebrewTexts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsRelation
    {
        public int WordsRelationID { get; set; }
        public int FromWordID { get; set; }
        public int ToWordID { get; set; }
        public string RelationType { get; set; }
        public string Comment { get; set; }
    
        public virtual WordsDictionary WordsDictionary { get; set; }
        public virtual WordsDictionary WordsDictionary1 { get; set; }
    }
}
