USE KiMeTztion;

DROP TABLE IF EXISTS TALMUD_MASSECHET;
DROP TABLE IF EXISTS MASSECHET;
DROP TABLE IF EXISTS TALMUD;
DROP TABLE IF EXISTS SEDER;
DROP TABLE IF EXISTS TOSHBA;

CREATE TABLE TOSHBA
(TOSHBA_WORK_ID INT NOT NULL IDENTITY,
WORK_NAME NVARCHAR(200) NOT NULL,
CONSTRAINT PK_TOSHBA PRIMARY KEY  (TOSHBA_WORK_ID)
);


CREATE TABLE SEDER
(SEDER_ID INT NOT NULL IDENTITY,
TOSHBA_id INT NOT NULL,
SEDER_NAME NVARCHAR(120) NOT NULL,
ORDER_ID INT NOT NULL,
CONSTRAINT PK_SEDER PRIMARY KEY  (SEDER_ID),
CONSTRAINT FK_SEDER_TOSHBA FOREIGN KEY (TOSHBA_ID) REFERENCES TOSHBA(TOSHBA_WORK_ID)
);


CREATE TABLE MASSECHET
(MASSECHET_ID INT IDENTITY,
SEDER_ID INT NOT NULL,
MASSECHET_NAME NVARCHAR(120) NOT NULL,
CONSTRAINT PK_MASSECHET PRIMARY KEY  (MASSECHET_ID),
CONSTRAINT FK_MASSECHET_SEDER FOREIGN KEY (SEDER_ID) REFERENCES dbo.SEDER (SEDER_ID)
);


CREATE TABLE TALMUD
(
TALMUD_ID INT NOT NULL,
TALMUD_NAME NVARCHAR(20) NOT NULL,
CONSTRAINT PK_TALMUD PRIMARY KEY (TALMUD_ID)
); 

CREATE TABLE TALMUD_MASSECHET
(
TALMUD_ID INT NOT NULL,
MASSECHET_ID INT NOT NULL,
CONSTRAINT FK_TM_MASSECHET FOREIGN KEY (MASSECHET_ID) REFERENCES MASSECHET(MASSECHET_ID),
CONSTRAINT FK_TM_TALMUD FOREIGN KEY (TALMUD_ID) REFERENCES TALMUD(TALMUD_ID)
)