USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS MASSECHET;

CREATE TABLE MASSECHET
(
MASSECHET_ID INT IDENTITY,
SEDER_ID INT NOT NULL,
MASSECHET_NAME NVARCHAR(120) NOT NULL,
MASSECHET_NUMBER_IN_SEDER INT NOT NULL,
CONSTRAINT PK_MASSECHET PRIMARY KEY  (MASSECHET_ID),
CONSTRAINT FK_MASSECHET_SEDER FOREIGN KEY (SEDER_ID) REFERENCES SEDER (SEDER_ID)
);
