USE KiMeTztion;

DROP TABLE IF EXISTS MASSECHET_PEREK

CREATE TABLE MASSECHET_PEREK
(
PEREK_ID INT NOT NULL IDENTITY
,MASSECHET_ID INT NOT NULL
,PEREK_NUM INT NOT NULL
,PEREK_NAME NVARCHAR(120) NOT NULL
CONSTRAINT PK_MASSECHET_PEREK PRIMARY KEY (TALMUD_PEREK_WORD_ID),
CONSTRAINT FK_MASSECHET_ID FOREIGN KEY (MASSECHET_ID) REFERENCES MASSECHET(MASSECHET_ID),
);

