USE KiMeTztion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS MASSECHET_PEREK

CREATE TABLE MASSECHET_PEREK
(
PEREK_ID INT NOT NULL IDENTITY
,MASSECHET_ID INT NOT NULL
,PEREK_NUM INT NOT NULL
,PEREK_NAME NVARCHAR(120) NOT NULL
,DAF_START INT NOT NULL
,AMUD_START INT NOT NULL
,DAF_END INT NOT NULL
,AMUD_END INT NOT NULL
CONSTRAINT PK_MASSECHET_PEREK PRIMARY KEY (PEREK_ID),
CONSTRAINT FK_MASSECHET_ID FOREIGN KEY (MASSECHET_ID) REFERENCES MASSECHET(MASSECHET_ID),
);

