USE KiMeTztion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS BAVLI_DAF

CREATE TABLE BAVLI_DAF
(
 BAVLI_DAF_ID INT NOT NULL IDENTITY
,PEREK_ID INT
,DAF_NUM INT NOT NULL --INTEGER VALUE
,DAF_NAME NVARCHAR(3) --VALUE IN HEBREW LETTERS
,AMUD_NUM INT NOT NULL
,AMUD_NAME NVARCHAR(1) NOT NULL
CONSTRAINT PK_BAVLI_DAF PRIMARY KEY (BAVLI_DAF_ID),
CONSTRAINT FK_BAVLI_DAF_PEREK_ID FOREIGN KEY (PEREK_ID) REFERENCES MASSECHET_PEREK(PEREK_ID)
);