USE KiMeTztion;

DROP TABLE IF EXISTS BAVLI_DAF

CREATE TABLE BAVLI_DAF
(
 BAVLI_DAF_ID INT NOT NULL IDENTITY
,DAF_NUM INT NOT NULL --INTEGER VALUE
,DAF_NAME NVARCHAR(3) --VALUE IN HEBREW LETTERS
,AMUD_NUM INT NOT NULL
,AMUD_NAME NVARCHAR(1) NOT NULL
);