USE KiMeTztion;

DROP TABLE IF EXISTS BAVLI_DAF_WORD

CREATE TABLE BAVLI_DAF_WORD
(
 BAVLI_DAF_WORD_ID INT NOT NULL IDENTITY
,PEREK_ID INT -- FK FROM PEREK 
,BAVLI_DAF_ID INT -- FK FROM BAVLI_DAF
,ROW_ID INT NOT NULL
,W_DELETED bit NOT NULL
,W_ADDED bit NOT NULL
,WORD_POSITION INT NOT NULL
,WORD_TYPE BIT NOT NULL -- mishna or gemara
,WORD NVARCHAR (50) NOT NULL
);
