USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS BAVLI_DAF_WORD

CREATE TABLE BAVLI_DAF_WORD
(
 BAVLI_DAF_WORD_ID INT NOT NULL IDENTITY
,PEREK_ID INT -- FK FROM PEREK 
,BAVLI_DAF_AMUD_ID INT -- FK FROM BAVLI_DAF
,ROW_ID INT NOT NULL
,W_DELETED bit NOT NULL
,W_ADDED bit NOT NULL
,WORD_POSITION INT NOT NULL
,WORD_TYPE BIT NOT NULL -- mishna or gemara
,WORD NVARCHAR (50) NOT NULL
CONSTRAINT PK_BAVLI_DAF_WORD PRIMARY KEY (BAVLI_DAF_WORD_ID),
CONSTRAINT FK_BAVLI_DAF_WORD_PEREK_ID FOREIGN KEY (PEREK_ID) REFERENCES MASSECHET_PEREK(PEREK_ID),
CONSTRAINT FK_BAVLI_DAF_AMUD_ID FOREIGN KEY (BAVLI_DAF_AMUD_ID) REFERENCES BAVLI_DAF(BAVLI_DAF_AMUD_ID)
);
