USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_MASSECHET_WORD

CREATE TABLE TBL_MASSECHET_WORD
(
WORD_ID INT NOT NULL IDENTITY 
,MASSECHET_DAF_ID INT NOT NULL
,PEREK_ID INT NOT NULL
,ROW_ID INT NOT NULL
,W_DELETED bit NOT NULL
,W_ADDED bit NOT NULL
,WORD_POSITION INT NOT NULL
,WORD_TYPE BIT NOT NULL -- mishna or gemara
,WORD NVARCHAR (50) NOT NULL
,CONSTRAINT PK_MASSECHET_WORD PRIMARY KEY (WORD_ID)
,CONSTRAINT FK_MASSECHET_WORD_MASSECHET_DAF_ID FOREIGN KEY (MASSECHET_DAF_ID) REFERENCES TBL_MASSECHET_DAF (MASSECHET_DAF_ID)
,CONSTRAINT FK_MASSECHET_WORD_MASSECHET_PEREK_ID FOREIGN KEY (PEREK_ID) REFERENCES TBL_MASSECHET_PEREK (PEREK_ID)
);
