USE KiMeTztion;

DROP TABLE IF EXISTS MASSECHET_PEREK

CREATE TABLE MASSECHET_PEREK
(
TALMUD_PEREK_WORD_ID INT NOT NULL IDENTITY,
TALMUD_MASSECHET_ID INT NOT NULL,
PEREK_NUM INT NOT NULL,
PEREK_NAME NVARCHAR(120) NOT NULL,
DAF NVARCHAR(5) NOT NULL,
AMUD NVARCHAR(1) NOT NULL,
AMUD_NUM INT NOT NULL,
ROW INT NOT NULL,
WORD NVARCHAR (50) NOT NULL,
WORD_POSITION INT NOT NULL
CONSTRAINT PK_MASSECHET_PEREK PRIMARY KEY (TALMUD_PEREK_WORD_ID),
CONSTRAINT FK_TALMUD_MASSECHET_ID FOREIGN KEY (TALMUD_MASSECHET_ID) REFERENCES TALMUD_MASSECHET(TALMUD_MASSECHET_ID),
)