USE KiMeTztion;

DROP TABLE IF EXISTS SEDER;

CREATE TABLE SEDER
(
SEDER_ID INT NOT NULL IDENTITY,
TOSHBA_id INT NOT NULL,
SEDER_NAME NVARCHAR(120) NOT NULL,
ORDER_ID INT NOT NULL,
CONSTRAINT PK_SEDER PRIMARY KEY  (SEDER_ID),
CONSTRAINT FK_SEDER_TOSHBA FOREIGN KEY (TOSHBA_ID) REFERENCES TOSHBA (TOSHBA_WORK_ID)
);