USE KiMeTztion;

DROP TABLE IF EXISTS TALMUD_TYPE;

CREATE TABLE TALMUD_TYPE
(
TALMUD_ID INT NOT NULL IDENTITY,
TOSHBA_id INT NOT NULL,
TALMUD_NAME NVARCHAR(20) NOT NULL,
CONSTRAINT PK_TALMUD PRIMARY KEY (TALMUD_ID),
CONSTRAINT FK_TOSHBA_id FOREIGN KEY (TOSHBA_id) REFERENCES TOSHBA (TOSHBA_WORK_ID)
)
