USE KiMeTztion;

DROP TABLE IF EXISTS TALMUD_SEDER;

CREATE TABLE TALMUD_SEDER
(
TALMUD_SEDER_ID INT NOT NULL IDENTITY,
SEDER_ID INT NOT NULL,
TALMUD_ID INT NOT NULL,
CONSTRAINT PK_TALMUD_SEDER PRIMARY KEY (TALMUD_SEDER_ID),
CONSTRAINT FK_SEDER_ID_SEDER_ID FOREIGN KEY (SEDER_ID) REFERENCES SEDER (SEDER_ID),
CONSTRAINT FK_TALMUD_ID_TALMUD_ID FOREIGN KEY (TALMUD_ID) REFERENCES TALMUD_TYPE (TALMUD_ID)
);
