CREATE TABLE [dbo].[TBL_TANAKH_SEFER_PEREK] (
    [SEFER_PEREK_ID] INT IDENTITY (1, 1) NOT NULL,
    [PEREK_ID]       INT NOT NULL,
    [SEFER_ID]       INT NOT NULL,
    CONSTRAINT [PK_TBL_TANAKH_SEFER_PEREK_SEFER_PEREK_ID] PRIMARY KEY CLUSTERED ([SEFER_PEREK_ID] ASC),
    CONSTRAINT [FK_TBL_TANAKH_SEFER_PEREK_PEREK_ID] FOREIGN KEY ([PEREK_ID]) REFERENCES [dbo].[TBL_TANAKH_PEREK] ([PEREK_ID]),
    CONSTRAINT [FK_TBL_TANAKH_SEFER_PEREK_SEFER_ID] FOREIGN KEY ([SEFER_ID]) REFERENCES [dbo].[TBL_TANAKH_SEFER] ([SEFER_ID])
);

