CREATE TABLE [dbo].[TBL_USER_BAVLI_WORD_DEF] (
    [USER_BAVLI_WORD_ID] INT             IDENTITY (1, 1) NOT NULL,
    [MASSECHET_NAME]     NVARCHAR (50)   NULL,
    [DAF_NAME]           NVARCHAR (3)    NULL,
    [AMUD_NAME]          NVARCHAR (1)    NULL,
    [ROW_ID]             INT             NULL,
    [WORD_POSITION]      INT             NULL,
    [WORD]               NVARCHAR (50)   NULL,
    [WORD_DEF]           NVARCHAR (3000) NULL,
    CONSTRAINT [PK_USER_BAVLI_WORD_DEF_ID] PRIMARY KEY CLUSTERED ([USER_BAVLI_WORD_ID] ASC)
);

