CREATE TABLE [dbo].[TBL_TANAKH_PEREK] (
    [PEREK_ID]         INT          IDENTITY (1, 1) NOT NULL,
    [PEREK_NUM]        INT          NOT NULL,
    [PEREK_HEBREW_NUM] NVARCHAR (3) NULL,
    CONSTRAINT [PK_TBL_TANAKH_PEREK_PEREK_ID] PRIMARY KEY CLUSTERED ([PEREK_ID] ASC)
);

