CREATE TABLE [dbo].[TBL_INITIALS_YERUSHALMI_WORD] (
    [IYW_ID]             INT IDENTITY (1, 1) NOT NULL,
    [INITIALS_ID]        INT NOT NULL,
    [YERUSHALMI_WORD_ID] INT NOT NULL,
    CONSTRAINT [PK_TBL_INITIALS_YERUSHALMI_WORD_IBW_ID] PRIMARY KEY CLUSTERED ([IYW_ID] ASC),
    CONSTRAINT [FK_TBL_INITIALS_YERUSHALMI_WORD_INITIALS_ID] FOREIGN KEY ([INITIALS_ID]) REFERENCES [dbo].[TBL_INITIALS] ([INITIALS_ID]),
    CONSTRAINT [FK_TBL_INITIALS_YERUSHALMI_WORD_WORD_ID] FOREIGN KEY ([YERUSHALMI_WORD_ID]) REFERENCES [dbo].[TBL_YERUSHALMI_MASSECHET_WORD] ([YERUSHALMI_WORD_ID])
);

