CREATE TABLE [dbo].[TBL_MASSECHET_DAF] (
    [MASSECHET_DAF_ID] INT IDENTITY (1, 1) NOT NULL,
    [MASSECHET_ID]     INT NOT NULL,
    [DAF_AMUD_ID]      INT NOT NULL,
    CONSTRAINT [PK_MASSECHET_DAF] PRIMARY KEY CLUSTERED ([MASSECHET_DAF_ID] ASC),
    CONSTRAINT [FK_MASSECHET_DAF_DAF_AMUD_ID] FOREIGN KEY ([DAF_AMUD_ID]) REFERENCES [dbo].[TBL_DAF] ([DAF_AMUD_ID]),
    CONSTRAINT [FK_MASSECHET_DAF_MASSECHET_ID] FOREIGN KEY ([MASSECHET_ID]) REFERENCES [dbo].[TBL_MASSECHET] ([MASSECHET_ID])
);

