CREATE TABLE [dbo].[TBL_BAVLI_WORD] (
    [BAVLI_WORD_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [MASSECHET_DAF_ID] INT           NOT NULL,
    [PEREK_ID]         INT           NOT NULL,
    [ROW_ID]           INT           NOT NULL,
    [W_DELETED]        BIT           NOT NULL,
    [W_ADDED]          BIT           NOT NULL,
    [WORD_POSITION]    INT           NOT NULL,
    [WORD_TYPE]        BIT           NOT NULL,
    [WORD]             NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_BAVLI_WORD] PRIMARY KEY CLUSTERED ([BAVLI_WORD_ID] ASC),
    CONSTRAINT [FK_BAVLI_WORD_MASSECHET_DAF_ID] FOREIGN KEY ([MASSECHET_DAF_ID]) REFERENCES [dbo].[TBL_MASSECHET_DAF] ([MASSECHET_DAF_ID]),
    CONSTRAINT [FK_BAVLI_WORD_MASSECHET_PEREK_ID] FOREIGN KEY ([PEREK_ID]) REFERENCES [dbo].[TBL_MASSECHET_PEREK] ([PEREK_ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_TBL_BAVLI_WORD_WORD]
    ON [dbo].[TBL_BAVLI_WORD]([WORD] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TBL_BAVLI_WORD_ROW_ID]
    ON [dbo].[TBL_BAVLI_WORD]([ROW_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TBL_BAVLI_WORD_BAVLI_WORD_ID]
    ON [dbo].[TBL_BAVLI_WORD]([BAVLI_WORD_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TBL_BAVLI_WORD_WORD_POSITION]
    ON [dbo].[TBL_BAVLI_WORD]([WORD_POSITION] ASC);

