CREATE TABLE [dbo].[TBL_WORD_DEF] (
    [WORD_DEF_ID] INT            IDENTITY (1, 1) NOT NULL,
    [WORD_ID]     INT            NOT NULL,
    [WORD_DEF]    NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBL_WORD_DEF_ID] PRIMARY KEY CLUSTERED ([WORD_DEF_ID] ASC),
    CONSTRAINT [FK_TBL_WORD_DEF_WORD_ID] FOREIGN KEY ([WORD_ID]) REFERENCES [dbo].[TBL_WORD] ([WORD_ID])
);

