CREATE TABLE [dbo].[TBL_DIBOUR_HAMATRIL] (
    [DIBOUR_HAMATRIL_ID] INT            IDENTITY (1, 1) NOT NULL,
    [MASSECHET_ID]       INT            NOT NULL,
    [DAF_AMUD_ID]        INT            NOT NULL,
    [TYPE]               BIT            NOT NULL,
    [CONTENT]            NVARCHAR (150) NOT NULL,
    CONSTRAINT [PK_TBL_DIBOUR_HAMATRIL] PRIMARY KEY CLUSTERED ([DIBOUR_HAMATRIL_ID] ASC),
    CONSTRAINT [FK_TBL_DIBOUR_HAMATRIL_DAF_AMUD_ID] FOREIGN KEY ([DAF_AMUD_ID]) REFERENCES [dbo].[TBL_DAF] ([DAF_AMUD_ID]),
    CONSTRAINT [FK_TBL_DIBOUR_HAMATRIL_MASSECHET_ID] FOREIGN KEY ([MASSECHET_ID]) REFERENCES [dbo].[TBL_MASSECHET] ([MASSECHET_ID])
);

