CREATE TABLE [dbo].[TBL_REF_NIKKUD] (
    [NIKKUD_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [NIKKUD_NAME]        NVARCHAR (50) NOT NULL,
    [NIKKUD_HEBREW_NAME] NVARCHAR (50) NOT NULL,
    [NIKKUD]             NVARCHAR (50) NOT NULL,
    [UNICODE_VALUE]      NVARCHAR (50) NOT NULL,
    [HTML_CODE]          NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBL_REF_NIKKUD_NIKKUD_ID] PRIMARY KEY CLUSTERED ([NIKKUD_ID] ASC)
);

