CREATE TABLE [dbo].[TBL_LETTER] (
    [LETTER_ID]               INT IDENTITY (1, 1) NOT NULL,
    [WORD_ID]                 INT NOT NULL,
    [REF_LETTER_ID]           INT NOT NULL,
    [LETTER_POSITION_IN_WORD] INT NOT NULL,
    CONSTRAINT [PK_TBL_LETTER] PRIMARY KEY CLUSTERED ([LETTER_ID] ASC),
    CONSTRAINT [FK_TBL_LETTER_REF_LETTER_ID] FOREIGN KEY ([REF_LETTER_ID]) REFERENCES [dbo].[TBL_REF_LETTER] ([LETTER_ID]),
    CONSTRAINT [FK_TBL_LETTER_WORD_ID] FOREIGN KEY ([WORD_ID]) REFERENCES [dbo].[TBL_TANAKH_WORD] ([WORD_ID])
);

