CREATE TABLE [dbo].[TBL_YERUSAHLMI_WORD_WORD_DEF] (
    [YERUSHALMI_WORD_DEF_ID] INT IDENTITY (1, 1) NOT NULL,
    [YERUSHALMI_WORD_ID]     INT NOT NULL,
    [WORD_DEF_ID]            INT NOT NULL,
    CONSTRAINT [PK_TBL_YERUSAHLMI_WORD_WORD_DEF_YERUSHALMI_WORD_DEF_ID] PRIMARY KEY CLUSTERED ([YERUSHALMI_WORD_DEF_ID] ASC),
    CONSTRAINT [FK_TBL_YERUSAHLMI_WORD_WORD_DEF_WORD_DEF_ID] FOREIGN KEY ([WORD_DEF_ID]) REFERENCES [dbo].[TBL_WORD_DEF] ([WORD_DEF_ID]),
    CONSTRAINT [FK_TBL_YERUSAHLMI_WORD_WORD_DEF_WORD_ID] FOREIGN KEY ([YERUSHALMI_WORD_ID]) REFERENCES [dbo].[TBL_YERUSHALMI_WORD] ([YERUSHALMI_WORD_ID])
);



