CREATE TABLE [dbo].[TBL_TAAM_LETTER] (
    [TAAM_LETTER_ID] INT IDENTITY (1, 1) NOT NULL,
    [LETTER_ID]      INT NOT NULL,
    [TAAM_ID]        INT NOT NULL,
    CONSTRAINT [PK_TBL_TAAM_LETTER] PRIMARY KEY CLUSTERED ([TAAM_LETTER_ID] ASC),
    CONSTRAINT [FK_TBL_TAAM_LETTER_LETTER_ID] FOREIGN KEY ([LETTER_ID]) REFERENCES [dbo].[TBL_LETTER] ([LETTER_ID]),
    CONSTRAINT [FK_TBL_TAAM_LETTER_TAAM_ID] FOREIGN KEY ([TAAM_ID]) REFERENCES [dbo].[TBL_REF_TAAM] ([TAAM_ID])
);

