CREATE TABLE [dbo].[TBL_REF_LETTER_ROLE] (
    [LETTER_ROLE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [LETTER_ROLES]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBL_REF_LETTER_ROLE_LETTER_ROLE_ID] PRIMARY KEY CLUSTERED ([LETTER_ROLE_ID] ASC)
);

