CREATE TABLE [dbo].[TBL_YERUSHALMI_HALACHA] (
    [HALACHA_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [HALACHA_NUM]  INT          NOT NULL,
    [HALACHA_NAME] NVARCHAR (2) NULL,
    CONSTRAINT [PK_YERUSHALMI_HALACHA] PRIMARY KEY CLUSTERED ([HALACHA_ID] ASC)
);

