CREATE TABLE [dbo].[TBL_USER_YERUSHALMI_WORDS] (
    [USER_YERUSHALMI_WORD_ID] INT             IDENTITY (1, 1) NOT NULL,
    [MASSECHET_NAME]          NVARCHAR (50)   NULL,
    [PEREK_NAME]              NVARCHAR (3)    NULL,
    [HALACHA]                 NVARCHAR (1)    NULL,
    [WORD]                    NVARCHAR (50)   NULL,
    [WORD_DEF]                NVARCHAR (3000) NULL,
    CONSTRAINT [PK_USER_YERUSHALMI_WORDS_ID] PRIMARY KEY CLUSTERED ([USER_YERUSHALMI_WORD_ID] ASC)
);

