CREATE TABLE [dbo].[TBL_MASSECHET] (
    [MASSECHET_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [SEDER_ID]                  INT            NOT NULL,
    [MASSECHET_NAME]            NVARCHAR (120) NOT NULL,
    [MASSECHET_NUMBER_IN_SEDER] INT            NOT NULL,
    CONSTRAINT [PK_MASSECHET] PRIMARY KEY CLUSTERED ([MASSECHET_ID] ASC),
    CONSTRAINT [FK_MASSECHET_SEDER_ID] FOREIGN KEY ([SEDER_ID]) REFERENCES [dbo].[TBL_SEDER] ([SEDER_ID])
);

