CREATE TABLE [dbo].[TBL_WORD_COMPLETE] (
    [COMP_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [COMP_WORD]  NVARCHAR (50) NOT NULL,
    [COMPLETION] NVARCHAR (50) NULL,
    CONSTRAINT [PK_TBL_WORD_COMPLETE] PRIMARY KEY CLUSTERED ([COMP_ID] ASC)
);

