CREATE TABLE [dbo].[TBL_DAF] (
    [DAF_AMUD_ID] INT          IDENTITY (1, 1) NOT NULL,
    [DAF_NUM]     INT          NOT NULL,
    [DAF_NAME]    NVARCHAR (3) NULL,
    [AMUD_NUM]    INT          NOT NULL,
    [AMUD_NAME]   NVARCHAR (3) NOT NULL,
    CONSTRAINT [PK_TBL_DAF] PRIMARY KEY CLUSTERED ([DAF_AMUD_ID] ASC)
);

