CREATE TABLE [dbo].[TBL_NIKKUD_LETTER] (
    [NIKKUD_LETTER_ID] INT IDENTITY (1, 1) NOT NULL,
    [LETTER_ID]        INT NOT NULL,
    [NIKKUD_ID]        INT NOT NULL,
    CONSTRAINT [PK_TBL_NIKKUD_LETTER] PRIMARY KEY CLUSTERED ([NIKKUD_LETTER_ID] ASC),
    CONSTRAINT [FK_TBL_NIKKUD_LETTER_LETTER_ID] FOREIGN KEY ([LETTER_ID]) REFERENCES [dbo].[TBL_LETTER] ([LETTER_ID]),
    CONSTRAINT [FK_TBL_NIKKUD_LETTER_NIKKUD_ID] FOREIGN KEY ([NIKKUD_ID]) REFERENCES [dbo].[TBL_REF_NIKKUD] ([NIKKUD_ID])
);

