CREATE TABLE [dbo].[TBL_INITIAL_WORD_DEF] (
    [INIT_DEF_ID]      INT IDENTITY (1, 1) NOT NULL,
    [INITIALS_WORD_ID] INT NOT NULL,
    [WORD_DEF_ID]      INT NOT NULL,
    CONSTRAINT [PK_TBL_BAVLI_INITIAL_WORD_DEF] PRIMARY KEY CLUSTERED ([INIT_DEF_ID] ASC),
    CONSTRAINT [FK_BAVLI_INITIAL] FOREIGN KEY ([INITIALS_WORD_ID]) REFERENCES [dbo].[TBL_INITIALS_WORD] ([INITIALS_WORD_ID]),
    CONSTRAINT [FK_INITIAL_DEFITION] FOREIGN KEY ([WORD_DEF_ID]) REFERENCES [dbo].[TBL_WORD_DEF] ([WORD_DEF_ID])
);

