CREATE TABLE [dbo].[TBL_INITIALS] (
    [INITIALS_ID] INT           IDENTITY (1, 1) NOT NULL,
    [INITIALS]    NVARCHAR (50) NOT NULL,
    [EXPANDED]    NVARCHAR (50) NULL,
    [EXPAND_ID]   INT           NULL,
    CONSTRAINT [PK_TBL_INITIALS] PRIMARY KEY CLUSTERED ([INITIALS_ID] ASC)
);

