CREATE TABLE [dbo].[TBL_YERUSHALMI_MASSECHET_HALACHA] (
    [MASSECHET_HALACHA_ID] INT IDENTITY (1, 1) NOT NULL,
    [PEREK_ID]             INT NOT NULL,
    [HALACHA_ID]           INT NOT NULL,
    CONSTRAINT [PK_TBL_YERUSHALMI_MASSECHET_HALACHA] PRIMARY KEY CLUSTERED ([MASSECHET_HALACHA_ID] ASC),
    CONSTRAINT [FK_TBL_YERUSHALMI_MASSECHET_HALACHA_HALACHA_ID] FOREIGN KEY ([HALACHA_ID]) REFERENCES [dbo].[TBL_YERUSHALMI_HALACHA] ([HALACHA_ID]),
    CONSTRAINT [FK_TBL_YERUSHALMI_MASSECHET_HALACHA_MASSECHET_PEREK_ID] FOREIGN KEY ([PEREK_ID]) REFERENCES [dbo].[TBL_MASSECHET_PEREK] ([PEREK_ID])
);

