CREATE TABLE [dbo].[TBL_REF_TAAM] (
    [TAAM_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [TAAM]          NVARCHAR (50) NOT NULL,
    [UNICODE_VALUE] NVARCHAR (50) NOT NULL,
    [HTML_CODE]     NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBL_REF_TAAM_TAAM_ID] PRIMARY KEY CLUSTERED ([TAAM_ID] ASC)
);

