CREATE TABLE [dbo].[TBL_TANAKH_PEREK_PASUK] (
    [PEREK_PASUK_ID] INT IDENTITY (1, 1) NOT NULL,
    [SEFER_PEREK_ID] INT NOT NULL,
    [PASUK_ID]       INT NOT NULL,
    CONSTRAINT [PK_TBL_TANAKH_PEREK_PASUK_PEREK_PASUK_ID] PRIMARY KEY CLUSTERED ([PEREK_PASUK_ID] ASC),
    CONSTRAINT [FK_TBL_TANAKH_PEREK_PASUK_PASUK_ID] FOREIGN KEY ([PASUK_ID]) REFERENCES [dbo].[TBL_TANAKH_PASUK] ([PASUK_ID]),
    CONSTRAINT [FK_TBL_TANAKH_PEREK_PASUK_PEREK_ID] FOREIGN KEY ([SEFER_PEREK_ID]) REFERENCES [dbo].[TBL_TANAKH_SEFER_PEREK] ([SEFER_PEREK_ID])
);

