CREATE TABLE [dbo].[TBL_CONTENT_WORD] (
    [CONTENT_WORD_ID] INT            IDENTITY (1, 1) NOT NULL,
    [CONTENT_WORD]    NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBL_CONTENT_WORD_CONTENT_WORD_ID] PRIMARY KEY CLUSTERED ([CONTENT_WORD_ID] ASC)
);

