CREATE TABLE [dbo].[TBL_SUBMITTED_DEF] (
    [DEFINITION_ID]  INT            IDENTITY (1, 1) NOT NULL,
    [STATUS]         BIT            DEFAULT ((0)) NOT NULL,
    [WORD_INITIAL]   NVARCHAR (10)  NOT NULL,
    [MASSECHET_NAME] NVARCHAR (50)  NOT NULL,
    [DAF_NAME]       NVARCHAR (3)   NOT NULL,
    [AMUD_NAME]      NVARCHAR (3)   NOT NULL,
    [ROW_ID]         NVARCHAR (3)   NOT NULL,
    [SUBMITED_DEF]   NVARCHAR (200) NOT NULL,
    CONSTRAINT [PK_TBL_SUBMIT_DEFINITIONS] PRIMARY KEY CLUSTERED ([DEFINITION_ID] ASC)
);

