CREATE TABLE [dbo].[TBL_MASSECHET_PEREK] (
    [PEREK_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [MASSECHET_ID] INT            NOT NULL,
    [PEREK_NUM]    INT            NOT NULL,
    [PEREK_NAME]   NVARCHAR (120) NOT NULL,
    CONSTRAINT [PK_MASSECHET_PEREK] PRIMARY KEY CLUSTERED ([PEREK_ID] ASC),
    CONSTRAINT [FK_MASSECHET_PEREK_PEREK_ID] FOREIGN KEY ([MASSECHET_ID]) REFERENCES [dbo].[TBL_MASSECHET] ([MASSECHET_ID])
);

