CREATE TABLE [dbo].[TBL_INITIALS_BAVLI_WORD] (
    [IBW_ID]        INT IDENTITY (1, 1) NOT NULL,
    [INITIALS_ID]   INT NOT NULL,
    [BAVLI_WORD_ID] INT NOT NULL,
    CONSTRAINT [PK_TBL_INITIALS_BAVLI_WORD_IBW_ID] PRIMARY KEY CLUSTERED ([IBW_ID] ASC),
    CONSTRAINT [FK_TBL_INITIALS_BAVLI_WORD_INITIALS_ID] FOREIGN KEY ([INITIALS_ID]) REFERENCES [dbo].[TBL_INITIALS] ([INITIALS_ID]),
    CONSTRAINT [FK_TBL_INITIALS_BAVLI_WORD_WORD_ID] FOREIGN KEY ([BAVLI_WORD_ID]) REFERENCES [dbo].[TBL_BAVLI_WORD] ([BAVLI_WORD_ID])
);

