CREATE TABLE [dbo].[TBL_REF_LETTER] (
    [LETTER_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [LETTER_NUMBER] INT           NOT NULL,
    [LETTER_NAME]   NVARCHAR (50) NOT NULL,
    [LETTER]        NVARCHAR (1)  NOT NULL,
    [UNICODE_VALUE] NVARCHAR (50) NOT NULL,
    [HTML_CODE]     NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBL_REF_LETTER] PRIMARY KEY CLUSTERED ([LETTER_ID] ASC)
);

