CREATE TABLE [dbo].[TBL_SEDER] (
    [SEDER_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [SEDER_NAME] NVARCHAR (120) NOT NULL,
    [ORDER_ID]   INT            NOT NULL,
    CONSTRAINT [PK_SEDER] PRIMARY KEY CLUSTERED ([SEDER_ID] ASC)
);

