use KiMeTzion

select CAST(ROUND(max((A.daf_amud_id)/2.0),0) AS INT)[daf]
, B.MASSECHET_NAME 
, B.MASSECHET_ID
from TBL_MASSECHET_DAF A join TBL_MASSECHET B ON A.MASSECHET_ID=B.MASSECHET_ID
where B.MASSECHET_NAME NOT IN (N'שקלים')
GROUP BY B.MASSECHET_NAME , B.MASSECHET_ID
ORDER BY B.MASSECHET_ID

select sum(daf) total_pages
FROM (
select CAST(ROUND(max((A.daf_amud_id)/2.0),0) AS INT)[daf]
, B.MASSECHET_NAME 
, B.MASSECHET_ID
from TBL_MASSECHET_DAF A join TBL_MASSECHET B ON A.MASSECHET_ID=B.MASSECHET_ID
where B.MASSECHET_NAME NOT IN (N'שקלים')
GROUP BY B.MASSECHET_NAME , B.MASSECHET_ID
ORDER BY B.MASSECHET_ID
) X