USE KiMeTzion

select L.LETTER_POSITION_IN_WORD,RL.LETTER,RTM.TAAM_NAME_SEFARADE, RN.NIKKUD_HEBREW_NAME
FROM 
TBL_LETTER L --
JOIN TBL_REF_LETTER RL ON L.REF_LETTER_ID = RL.LETTER_ID
JOIN TBL_TANAKH_WORD TW ON L.WORD_ID = TW.WORD_ID
JOIN TBL_TANAKH_PEREK_PASUK TPP ON TW.PEREK_PASUK_ID = TPP.PEREK_PASUK_ID
JOIN TBL_TANAKH_SEFER_PEREK TSP ON TSP.SEFER_PEREK_ID = TPP.SEFER_PEREK_ID
JOIN TBL_TANAKH_SEFER TS ON TS.SEFER_ID = TSP.SEFER_ID
-- get taamim:
LEFT JOIN TBL_TAAM_LETTER TL ON TL.LETTER_ID=l.LETTER_ID
LEFT JOIN TBL_REF_TAAM RT ON RT.TAAM_ID=TL.TAAM_ID
LEFT JOIN TBL_REF_TAAM_NAME RTM ON RTM.TAAM_ID=RT.TAAM_ID
--get nikkud
LEFT JOIN TBL_NIKKUD_LETTER NL ON L.LETTER_ID = NL.LETTER_ID
LEFT JOIN TBL_REF_NIKKUD RN ON NL.NIKKUD_ID=RN.NIKKUD_ID
WHERE 
TS.SEFER_ENGLISH_NAME = 'Vaikra'
AND TW.WORD_POSITION =1
AND TSP.PEREK_ID = 19
AND TPP.PASUK_ID =2

ORDER BY ts.SEFER_ID,TSP.PEREK_ID,TPP.PASUK_ID, L.LETTER_POSITION_IN_WORD
--FOR XML PATH ('')