USE KiMeTzion

--DECLARE @searchTerm NVARCHAR(120) = N'Shalshelet'
select SEFER_ENGLISH_NAME
,PEREK_ID
,PASUK_ID
,STRING_AGG(FULL_WORD, ' ') [pasuk_text]
FROM (
SELECT distinct 
TS.SEFER_ENGLISH_NAME
,TSP.PEREK_ID
,TPP.PASUK_ID
,tw.WORD_POSITION
,TW.FULL_WORD
FROM 
TBL_LETTER L 
JOIN TBL_TANAKH_WORD TW ON L.WORD_ID = TW.WORD_ID
JOIN TBL_TANAKH_PEREK_PASUK TPP ON TW.PEREK_PASUK_ID = TPP.PEREK_PASUK_ID
JOIN TBL_TANAKH_SEFER_PEREK TSP ON TSP.SEFER_PEREK_ID = TPP.SEFER_PEREK_ID
JOIN TBL_TANAKH_SEFER TS ON TS.SEFER_ID = TSP.SEFER_ID
LEFT JOIN TBL_TAAM_LETTER TL ON tl.LETTER_ID=l.LETTER_ID
LEFT JOIN TBL_REF_TAAM RT ON RT.TAAM_ID=TL.TAAM_ID
LEFT JOIN TBL_REF_TAAM_NAME RTM  ON RTM.TAAM_ID=RT.TAAM_ID

WHERE TPP.PEREK_PASUK_ID = 5560
AND (RT.TAAM_ID =14 OR RT.TAAM_ID IS NULL)
) X
group by SEFER_ENGLISH_NAME
,PEREK_ID
,PASUK_ID