USE KiMeTzion

--DECLARE @searchTerm NVARCHAR(120) = N'Shalshelet'

SELECT 
TS.SEFER_ENGLISH_NAME
,TSP.PEREK_ID
,TPP.PASUK_ID
,TW.WORD
,TW.FULL_WORD
FROM 
--TBL_REF_TAAM_NAME RTM 
--JOIN TBL_REF_TAAM RT ON RTM.TAAM_ID=RT.	TAAM_ID
--JOIN TBL_TAAM_LETTER TL ON RT.TAAM_ID=TL.TAAM_ID
--JOIN TBL_LETTER L ON tl.LETTER_ID=l.LETTER_ID
TBL_TANAKH_WORD TW --ON L.WORD_ID = TW.WORD_ID
JOIN TBL_TANAKH_PEREK_PASUK TPP ON TW.PEREK_PASUK_ID = TPP.PEREK_PASUK_ID
JOIN TBL_TANAKH_SEFER_PEREK TSP ON TSP.SEFER_PEREK_ID = TPP.SEFER_PEREK_ID
JOIN TBL_TANAKH_SEFER TS ON TS.SEFER_ID = TSP.SEFER_ID

WHERE TW.WORD like '%כשית%'
--and  TW.WORD not like 'ע%'
--and  TW.WORD not like 'ש%'
--and  TW.WORD not like '%זכ%'
--and  TW.WORD not like 'מש%'
ORDER BY ts.SEFER_ID,TSP.PEREK_ID,TPP.PASUK_ID