USE KiMeTzion_old

--DECLARE @searchTerm NVARCHAR(120) = N'Shalshelet'
select * from(
select 
SEFER_ID
,SEFER_ENGLISH_NAME
,PEREK_ID
,PASUK_ID
,STRING_AGG(WORD, ' ') WITHIN GROUP (ORDER BY WORD_ID ASC) [pasuk_text]
FROM (
SELECT distinct 
TS.SEFER_ENGLISH_NAME
,TS.SEFER_ID
,TSP.PEREK_ID
,TPP.PASUK_ID
,tw.WORD_POSITION
,TW.WORD
,TW.WORD_ID
FROM 
TBL_LETTER L 
JOIN TBL_TANAKH_WORD TW ON L.WORD_ID = TW.WORD_ID
JOIN TBL_TANAKH_PEREK_PASUK TPP ON TW.PEREK_PASUK_ID = TPP.PEREK_PASUK_ID
JOIN TBL_TANAKH_SEFER_PEREK TSP ON TSP.SEFER_PEREK_ID = TPP.SEFER_PEREK_ID
JOIN TBL_TANAKH_SEFER TS ON TS.SEFER_ID = TSP.SEFER_ID

) X
group by 
SEFER_ID
,SEFER_ENGLISH_NAME
,PEREK_ID
,PASUK_ID

)A where A.pasuk_text like N'%ה%ר%ב%ד%ו%ד%י%צ%ח%ק%'
order by 1,3,4

