CREATE PROCEDURE P_GET_INITIALS  
@INITIAL NVARCHAR(30)  
  
AS  
  
BEGIN  
  
SELECT a.MASSECHET_NAME, a.DAF_NAME, a.AMUD_NAME, a.ROW_ID
FROM TBL_USER_BAVLI_INITIALS a   
WHERE a.EXPANDED IS NULL
and INITIAL = @INITIAL  
  
END