CREATE PROCEDURE P_GET_INITIALS  
@INITIAL NVARCHAR(30)  
  
AS  
  
  
BEGIN  
  
SELECT a.MASSECHET_NAME, a.DAF_NAME, a.AMUD_NAME, a.ROW_ID  
FROM TBL_USER_INITIALS a   
LEFT JOIN TBL_SUBMITED_DEF b ON b.WORD_INITIAL = a.INITIAL and a.MASSECHET_NAME = b.MASSECHET_NAME and a.DAF_NAME = b.DAF_NAME and a.AMUD_NAME = b.AMUD_NAME and a.ROW_ID = b.ROW_ID  
WHERE b.WORD_INITIAL is NULL  
and b.MASSECHET_NAME is null  
and b.DAF_NAME is null  
and b.AMUD_NAME is null  
and b.ROW_ID is null  
and INITIAL = @INITIAL  
  
END