USE master
GO

-- Drop the database if it already exists
IF  EXISTS (
	SELECT name 
		FROM sys.databases 
		WHERE name = N'KiMeTztion'
)
DROP DATABASE KiMeTztion
GO

CREATE DATABASE KiMeTztion
GO


USE KiMeTztion;

DROP TABLE IF EXISTS TALMUD_MASSECHET;
DROP TABLE IF EXISTS MASSECHET;
DROP TABLE IF EXISTS TALMUD_TYPE;
DROP TABLE IF EXISTS SEDER;
DROP TABLE IF EXISTS TOSHBA;

CREATE TABLE TOSHBA
(
TOSHBA_WORK_ID INT NOT NULL IDENTITY,
WORK_NAME NVARCHAR(200) NOT NULL,
CONSTRAINT PK_TOSHBA PRIMARY KEY  (TOSHBA_WORK_ID)
);


CREATE TABLE SEDER
(
SEDER_ID INT NOT NULL IDENTITY,
TOSHBA_id INT NOT NULL,
SEDER_NAME NVARCHAR(120) NOT NULL,
ORDER_ID INT NOT NULL,
CONSTRAINT PK_SEDER PRIMARY KEY  (SEDER_ID),
CONSTRAINT FK_SEDER_TOSHBA FOREIGN KEY (TOSHBA_ID) REFERENCES TOSHBA (TOSHBA_WORK_ID)
);


CREATE TABLE MASSECHET
(
MASSECHET_ID INT IDENTITY,
SEDER_ID INT NOT NULL,
MASSECHET_NAME NVARCHAR(120) NOT NULL,
MASSECHET_NUMBER_IN_SEDER INT NOT NULL,
CONSTRAINT PK_MASSECHET PRIMARY KEY  (MASSECHET_ID),
CONSTRAINT FK_MASSECHET_SEDER FOREIGN KEY (SEDER_ID) REFERENCES SEDER (SEDER_ID)
);


CREATE TABLE TALMUD_TYPE
(
TALMUD_ID INT NOT NULL IDENTITY,
TOSHBA_id INT NOT NULL,
TALMUD_NAME NVARCHAR(20) NOT NULL,
CONSTRAINT PK_TALMUD PRIMARY KEY (TALMUD_ID),
CONSTRAINT FKÉ_TOSHBA_id FOREIGN KEY (TOSHBA_id) REFERENCES TOSHBA (TOSHBA_WORK_ID)
); 

CREATE TABLE TALMUD_SEDER
(
TALMUD_SEDER_ID INT NOT NULL IDENTITY,
SEDER_ID INT NOT NULL,
TALMUD_ID INT NOT NULL,
CONSTRAINT PK_TALMUD_SEDER PRIMARY KEY (TALMUD_SEDER_ID),
CONSTRAINT FK_SEDER_ID_SEDER_ID FOREIGN KEY (SEDER_ID) REFERENCES SEDER (SEDER_ID),
CONSTRAINT FK_TALMUD_ID_TALMUD_ID FOREIGN KEY (TALMUD_ID) REFERENCES TALMUD_TYPE (TALMUD_ID)
);

CREATE TABLE TALMUD_MASSECHET
(
TALMUD_MASSECHET_ID INT NOT NULL IDENTITY,
MASSECHET_ID INT NOT NULL,
TALMUD_SEDER_ID INT NOT NULL,
CONSTRAINT PK_TALMUD_MASSECHET PRIMARY KEY (TALMUD_MASSECHET_ID),
CONSTRAINT FK_MASSECHET_ID FOREIGN KEY (MASSECHET_ID) REFERENCES MASSECHET(MASSECHET_ID),
CONSTRAINT FK_TALMUD_SEDER_ID FOREIGN KEY (TALMUD_SEDER_ID) REFERENCES TALMUD_SEDER(TALMUD_SEDER_ID)
)