USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_REF_LETTER;

CREATE TABLE TBL_REF_LETTER
(
LETTER_ID INT IDENTITY NOT NULL,
LETTER_NUMBER INT NOT NULL,
LETTER_NAME NVARCHAR(50) NOT NULL,
LETTER NVARCHAR(1) NOT NULL,
UNICODE_VALUE NVARCHAR(50) NOT NULL,
HTML_CODE NVARCHAR(50) NOT NULL,
CONSTRAINT PK_TBL_REF_LETTER PRIMARY KEY (LETTER_ID)
);