USE KiMeTzion;


DROP TABLE IF EXISTS TBL_REF_LETTER_ROLE;

SET NOCOUNT ON; 

CREATE TABLE TBL_REF_LETTER_ROLE
(
LETTER_ROLE_ID INT IDENTITY NOT NULL,
LETTER_ROLES NVARCHAR(50) NOT NULL
CONSTRAINT PK_TBL_REF_LETTER_ROLE_LETTER_ROLE_ID PRIMARY KEY (LETTER_ROLE_ID)
);