USE KiMeTzion;


DROP TABLE IF EXISTS TBL_REF_TAAM_NAME;

SET NOCOUNT ON; 

CREATE TABLE TBL_REF_TAAM_NAME
(
TAAM_NAME_ID INT IDENTITY NOT NULL,
TAAM_ID INT NOT NULL,
TAAM_NAME_ASCHENAZE NVARCHAR(50) NOT NULL,
TAAM_NAME_SEFARADE NVARCHAR(50) NOT NULL,
TAAM_NAME_TEMANI NVARCHAR(50) NOT NULL,
TAAM_ENGLISH_NAME NVARCHAR(50) NOT NULL,
CONSTRAINT PK_TBL_REF_TAAM_NAME_TAAM_ID PRIMARY KEY (TAAM_NAME_ID),
CONSTRAINT FK_REF_TAAM_NAME_TAAM_ID FOREIGN KEY (TAAM_ID) REFERENCES TBL_REF_TAAM (TAAM_ID)
);