USE KiMeTzion;

DROP TABLE IF EXISTS TBL_LETTER;

SET NOCOUNT ON; 

CREATE TABLE TBL_LETTER
(
LETTER_ID INT IDENTITY NOT NULL,
WORD_ID INT NOT NULL,
REF_LETTER_ID INT NOT NULL,
LETTER_POSITION_IN_WORD INT NOT NULL,
CONSTRAINT PK_TBL_LETTER PRIMARY KEY (LETTER_ID),
CONSTRAINT FK_TBL_LETTER_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES TBL_WORD (WORD_ID),
CONSTRAINT FK_TBL_LETTER_REF_LETTER_ID FOREIGN KEY (REF_LETTER_ID) REFERENCES TBL_REF_LETTER (LETTER_ID)
)