USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_TANAKH_PEREK;

CREATE TABLE TBL_TANAKH_PEREK
(
PEREK_ID INT IDENTITY,
PEREK_NUM INT NOT NULL,
PEREK_HEBREW_NUM NVARCHAR(3),
CONSTRAINT PK_TBL_TANAKH_PEREK_PEREK_ID PRIMARY KEY (PEREK_ID)
);