USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_TANAKH_PASUK;

CREATE TABLE TBL_TANAKH_PASUK
(
PASUK_ID INT IDENTITY,
PASUK_NUM INT NOT NULL,
PASUK_HEBREW_NUM NVARCHAR(3) NOT NULL,
CONSTRAINT PK_TBL_TANAKH_PASUK_PASUK_ID PRIMARY KEY (PASUK_ID)
);