USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_TANAKH_PEREK_PASUK;

CREATE TABLE TBL_TANAKH_PEREK_PASUK
(
PEREK_PASUK_ID INT IDENTITY,
PEREK_ID INT NOT NULL,
PASUK_ID INT NOT NULL,
CONSTRAINT PK_TBL_TANAKH_PEREK_PASUK_PEREK_PASUK_ID PRIMARY KEY (PEREK_PASUK_ID),
CONSTRAINT FK_TBL_TANAKH_PEREK_PASUK_PEREK_ID FOREIGN KEY (PEREK_ID) REFERENCES TBL_TANAKH_PEREK (PEREK_ID),
CONSTRAINT FK_TBL_TANAKH_PEREK_PASUK_PASUK_ID FOREIGN KEY (PASUK_ID) REFERENCES TBL_TANAKH_PASUK (PASUK_ID)
);