USE KiMeTzion;

DROP TABLE IF EXISTS TBL_INITIALS;

SET NOCOUNT ON;

CREATE TABLE TBL_INITIALS
(
INITIALS_ID INT IDENTITY NOT NULL,
INITIALS NVARCHAR (50) NOT NULL,
EXPANDED NVARCHAR (50) NOT NULL,
EXPAND_ID INT NOT NULL,
CONSTRAINT PK_TBL_INITIALS PRIMARY KEY (INITIALS_ID)
)