USE KiMeTzion;

DROP TABLE IF EXISTS TBL_INITIALS_WORD;

SET NOCOUNT ON;

CREATE TABLE TBL_INITIALS_WORD
(
WORD_ID INT IDENTITY NOT NULL,
INITIALS_ID INT NOT NULL,
SEQ_ID INT NOT NULL,
WORD NVARCHAR (50) NOT NULL,
CONSTRAINT PK_INITIALS_WORD PRIMARY KEY (WORD_ID),
CONSTRAINT FK_TBL_INITIALS_WORD_INITIALS_ID FOREIGN KEY (INITIALS_ID) REFERENCES TBL_INITIALS (INITIALS_ID)