USE KiMeTzion;

DROP TABLE IF EXISTS TBL_WORD_COMPLETE;

SET NOCOUNT ON;

CREATE TABLE TBL_WORD_COMPLETE
(
COMP_ID INT IDENTITY NOT NULL,
COMP_WORD NVARCHAR(50) NOT NULL,
COMPLETION NVARCHAR(50) NULL,
CONSTRAINT PK_TBL_WORD_COMPLETE PRIMARY KEY (COMP_ID)
)
