SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_INITIALS_BAVLI_WORD

CREATE TABLE TBL_INITIALS_MASSECHET_WORD
(
IBW_ID int identity,
INITIALS_ID INT NOT NULL,
BAVLI_WORD_ID INT NOT NULL,
CONSTRAINT PK_TBL_INITIALS_MASSECHET_WORD_IBW_ID PRIMARY KEY (IBW_ID),
CONSTRAINT FK_TBL_INITIALS_MASSECHET_WORD_INITIALS_ID FOREIGN KEY (INITIALS_ID) REFERENCES TBL_INITIALS (INITIALS_ID),
CONSTRAINT FK_TBL_INITIALS_MASSECHET_WORD_WORD_ID FOREIGN KEY (BAVLI_WORD_ID) REFERENCES TBL_BAVLI_WORD (BAVLI_WORD_ID)
)