USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_BIND_INITIALS_TO_WORD_ID

CREATE TABLE TBL_BIND_INITIALS_TO_WORD_ID
(
BIND_ID INT IDENTITY NOT NULL,
WORD_ID INT NOT NULL,
INITIALS_ID INT NOT NULL,
CONSTRAINT PK_TBL_BIND_INITIALS_TO_WORD_ID PRIMARY KEY (BIND_ID),
CONSTRAINT FK_TBL_BIND_INITIALS_TO_WORD_ID_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES TBL_MASSECHET_WORD (WORD_ID),
CONSTRAINT FK_TBL_BIND_INITIALS_TO_WORD_ID_INITIALS_ID FOREIGN KEY (INITIALS_ID) REFERENCES TBL_INITIALS (INITIALS_ID)
);
