USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_BIND_COMPLETION_TO_WORD_ID

CREATE TABLE TBL_BIND_COMPLETION_TO_WORD_ID
(
BIND_ID INT IDENTITY NOT NULL,
WORD_ID INT NOT NULL,
COMP_ID INT NOT NULL,
CONSTRAINT PK_TBL_BIND_COMPLETION_TO_WORD_ID PRIMARY KEY (BIND_ID),
CONSTRAINT FK_TBL_BIND_COMPLETION_TO_WORD_ID_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES TBL_MASSECHET_WORD (WORD_ID),
CONSTRAINT FK_TBL_BIND_COMPLETION_TO_WORD_ID_COMP_ID FOREIGN KEY (COMP_ID) REFERENCES TBL_WORD_COMPLETE (COMP_ID)
)
