SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_USER_INITIALS;

CREATE TABLE TBL_USER_INITIALS
(
USER_ID INT IDENTITY NOT NULL,
MASSECHET_NAME NVARCHAR(50),
DAF_NAME NVARCHAR(3),
AMUD_NAME NVARCHAR(1),
ROW_ID INT,
WORD_POSITION INT,
INITIAL NVARCHAR(50),
EXPANDED NVARCHAR(100),
EXPANDED_ID INT
);

