USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_YERUSHALMI_MASSECHET_PEREK;

CREATE TABLE TBL_YERUSHALMI_MASSECHET_PEREK
(
MASSECHET_PEREK_ID INT IDENTITY NOT NULL,
MASSECHET_ID INT NOT NULL,
PEREK_NUM INT NOT NULL,
PEREK_NAME NVARCHAR(2),
CONSTRAINT PK_MASSECHET_PEREK_ID PRIMARY KEY (MASSECHET_PEREK_ID),
CONSTRAINT FK_TBL_YERUSHALMI_MASSECHET_PEREK_MASSECHET_ID FOREIGN KEY (MASSECHET_ID) REFERENCES TBL_MASSECHET(MASSECHET_ID)
);