USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_YERUSHALMI_MASSECHET_HALACHA;

CREATE TABLE TBL_YERUSHALMI_MASSECHET_HALACHA
(
MASSECHET_HALACHA_ID INT IDENTITY NOT NULL,
MASSECHET_PEREK_ID INT NOT NULL,
HALACHA_ID INT NOT NULL,
CONSTRAINT PK_TBL_YERUSHALMI_MASSECHET_HALACHA PRIMARY KEY (MASSECHET_HALACHA_ID),
CONSTRAINT FK_TBL_YERUSHALMI_MASSECHET_HALACHA_MASSECHET_PEREK_ID FOREIGN KEY (MASSECHET_PEREK_ID) REFERENCES TBL_YERUSHALMI_MASSECHET_PEREK(MASSECHET_PEREK_ID),
CONSTRAINT FK_TBL_YERUSHALMI_MASSECHET_HALACHA_HALACHA_ID FOREIGN KEY (HALACHA_ID) REFERENCES TBL_YERUSHALMI_HALACHA(HALACHA_ID)
);