SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_INITIALS_YERUSHALMI_WORD

CREATE TABLE TBL_INITIALS_YERUSHALMI_WORD
(
IYW_ID int identity,
INITIALS_ID INT NOT NULL,
YERUSHALMI_WORD_ID INT NOT NULL,
CONSTRAINT PK_TBL_INITIALS_YERUSHALMI_WORD_IBW_ID PRIMARY KEY (IYW_ID),
CONSTRAINT FK_TBL_INITIALS_YERUSHALMI_WORD_INITIALS_ID FOREIGN KEY (INITIALS_ID) REFERENCES TBL_INITIALS (INITIALS_ID),
CONSTRAINT FK_TBL_INITIALS_YERUSHALMI_WORD_WORD_ID FOREIGN KEY (YERUSHALMI_WORD_ID) REFERENCES TBL_YERUSHALMI_MASSECHET_WORD (YERUSHALMI_WORD_ID)
)