SET NOCOUNT ON;

CREATE TABLE TBL_TALMUD_WORD_DEF (
WORD_DEF_ID INT IDENTITY NOT NULL,
WORD_DEF NVARCHAR(3000) NOT NULL,
TALMUD_TYPE BIT NOT NULL, --0 = bavli, 1 = yerushalmi
CONSTRAINT PK_TBL_TALMUD_WORD_DEF_WORD_DEF_ID PRIMARY KEY (WORD_DEF_ID)
)
