SET NOCOUNT ON;

CREATE TABLE TBL_YERUSAHLMI_WORD_WORD_DEF(
YERUSHALMI_WORD_DEF_ID INT IDENTITY NOT NULL
WORD_ID INT NOT NULL,
WORD_DEF_ID INT NOT NULL,
CONSTRAINT PK_TBL_YERUSAHLMI_WORD_WORD_DEF_YERUSHALMI_WORD_DEF_ID (YERUSHALMI_WORD_DEF_ID),
CONSTRAINT FK_TBL_YERUSAHLMI_WORD_WORD_DEF_WORD_ID FOREIGN KEY (WORD_ID) REFERENCES TBL_YERUSHALMI_MASSECHET_WORD (WORD_ID),
CONSTRAINT FK_TBL_YERUSAHLMI_WORD_WORD_DEF_WORD_DEF_ID FOREIGN KEY (WORD_DEF_ID) REFERENCES TBL_TALMUD_WORD_DEF (WORD_DEF_ID)
)