SET NOCOUNT ON;

CREATE TABLE TBL_BAVLI_WORD_WORD_DEF(
BAVLI_WORD_DEF_ID INT IDENTITY NOT NULL
BAVLI_WORD_ID INT NOT NULL,
WORD_DEF_ID INT NOT NULL,
CONSTRAINT PK_TBL_BAVLI_WORD_WORD_DEF_BAVLI_WORD_DEF_ID (BAVLI_WORD_DEF_ID),
CONSTRAINT FK_TBL_BAVLI_WORD_WORD_DEF_WORD_ID FOREIGN KEY (BAVLI_WORD_ID) REFERENCES TBL_BAVLI_WORD (BAVLI_WORD_ID),
CONSTRAINT FK_TBL_BAVLI_WORD_WORD_DEF_WORD_DEF_ID FOREIGN KEY (WORD_DEF_ID) REFERENCES TBL_TALMUD_WORD_DEF (WORD_DEF_ID)
)