SET NOCOUNT ON;

CREATE TABLE TBL_USER_BAVLI_WORD_DEF
(
USER_BAVLI_WORD_ID INT IDENTITY NOT NULL,
MASSECHET_NAME NVARCHAR(50),
DAF_NAME NVARCHAR(3),
AMUD_NAME NVARCHAR(1),
ROW_ID INT,
WORD_POSITION INT,
WORD NVARCHAR(50),
WORD_DEF NVARCHAR(3000),
CONSTRAINT PK_USER_BAVLI_WORD_DEF_ID PRIMARY KEY (USER_BAVLI_WORD_ID)
);