SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_USER_YERUSHALMI_WORDS;

CREATE TABLE TBL_USER_YERUSHALMI_WORDS
(
USER_YERUSHALMI_WORD_ID INT IDENTITY NOT NULL,
MASSECHET_NAME NVARCHAR(50),
PEREK_NAME NVARCHAR(3),
HALACHA NVARCHAR(1),
WORD NVARCHAR(50),
WORD_DEF NVARCHAR(3000),
CONSTRAINT PK_USER_YERUSHALMI_WORDS_ID PRIMARY KEY (USER_YERUSHALMI_WORD_ID)
);