SET NOCOUNT ON;

CREATE TABLE TBL_SUBMITED_YERUSHALMI_WORD_DEF(
SUBMITED_YERUSHALMI_WORD_DEF_ID INT IDENTITY NOT NULLת
MASSECHET_NAME NVARCHAR(50),
PEREK_NAME NVARCHAR(3),
HALACHA NVARCHAR(1),
WORD NVARCHAR(50),
SUBMITED_WORD_DEF NVARCHAR(3000),
CONSTRAINT PK_TBL_SUBMITED_YERUSHALMI_WORD_DEF_ID PRIMARY KEY (SUBMITED_YERUSHALMI_WORD_DEF_ID)
)