SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_USER_YERUSHALMI_INITIALS;

CREATE TABLE TBL_USER_YERUSHALMI_INITIALS
(
USER_ID INT IDENTITY NOT NULL,
STATUS BIT NOT NULL DEFAULT 0,
MASSECHET_NAME NVARCHAR(50),
HALACHA_NAME NVARCHAR(3),
PEREK_NAME NVARCHAR(1),
WORD_POSITION INT NOT NULL,
INITIAL NVARCHAR(50),
EXPANDED NVARCHAR(100),
EXPANDED_ID INT
);