SET NOCOUNT ON;

CREATE TABLE TBL_USER_YERUSHALMI_INITIALS
(
USER_ID INT IDENTITY NOT NULL,
MASSECHET_NAME NVARCHAR(50),
HALACHA_NAME NVARCHAR(3),
PEREK_NAME NVARCHAR(1),
INITIAL NVARCHAR(50),
EXPANDED NVARCHAR(100),
EXPANDED_ID INT
);