SET NOCOUNT ON;

CREATE TABLE TBL_SUBMITED_YERUSHALMI_DEF
(
DEFINITION_ID INT IDENTITY NOT NULL,
STATUS BIT NOT NULL DEFAULT 0,
WORD_INITIAL NVARCHAR(10) NOT NULL,
MASSECHET_NAME NVARCHAR(50) NOT NULL,
DAF_NAME NVARCHAR(3) NOT NULL,
AMUD_NAME NVARCHAR(3) NOT NULL,
ROW_ID NVARCHAR(3) NOT NULL,
SUBMITED_DEF NVARCHAR(200) NOT NULL,
CONSTRAINT PK_TBL_SUBMITED_YERUSHALMI_DEF_ID PRIMARY KEY (DEFINITION_ID)
)