USE KiMeTztion;

DROP TABLE IF EXISTS TALMUD_MASSECHET;

CREATE TABLE TALMUD_MASSECHET
(
TALMUD_MASSECHET_ID INT NOT NULL IDENTITY,
MASSECHET_ID INT NOT NULL,
TALMUD_SEDER_ID INT NOT NULL,
CONSTRAINT PK_TALMUD_MASSECHET PRIMARY KEY (TALMUD_MASSECHET_ID),
CONSTRAINT FK_MASSECHET_ID FOREIGN KEY (MASSECHET_ID) REFERENCES MASSECHET(MASSECHET_ID),
CONSTRAINT FK_TALMUD_SEDER_ID FOREIGN KEY (TALMUD_SEDER_ID) REFERENCES TALMUD_SEDER(TALMUD_SEDER_ID)
)