USE KiMeTzion;

SET NOCOUNT ON;

DROP TABLE IF EXISTS TBL_REF_NIKKUD

CREATE TABLE TBL_REF_NIKKUD
(
NIKKUD_ID INT IDENTITY NOT NULL,
NIKKUD_NAME NVARCHAR(50) NOT NULL,
NIKKUD_HEBREW_NAME NVARCHAR(50) NOT NULL,
NIKKUD NVARCHAR(50) NOT NULL,
CONSTRAINT PK_TBL_REF_NIKKUD_NIKKUD_ID PRIMARY KEY (NIKKUD_ID)
);