USE KiMeTzion;


DROP TABLE IF EXISTS TBL_REF_TAAM;

SET NOCOUNT ON; 

CREATE TABLE TBL_REF_TAAM
(
TAAM_ID INT IDENTITY NOT NULL,
TAAM NVARCHAR(50) NOT NULL,
TAAM_NAME_ASCHENAZE NVARCHAR(50) NOT NULL,
TAAM_NAME_SEFARADE NVARCHAR(50) NOT NULL,
TAAM_NAME_TEMANI NVARCHAR(50) NOT NULL,
TAAM_ENGLISH_NAME NVARCHAR(50) NOT NULL,
UNICODE_VALUE NVARCHAR(50) NOT NULL,
HTML_CODE NVARCHAR(50) NOT NULL,
CONSTRAINT PK_TBL_REF_TAAM_TAAM_ID PRIMARY KEY (TAAM_ID)
);