USE KiMeTzion
GO

DROP TABLE IF EXISTS TBL_LETTER;

SET NOCOUNT ON; 

CREATE TABLE TBL_LETTER
(
ID INT IDENTITY NOT NULL,
WORD_ID INT NOT NULL,
LETTER_ID INT NOT NULL,
LETTER_POSITION_IN_WORD INT NOT NULL,
CONSTRAINT PK_TBL_LETTER PRIMARY KEY (ID),
CONSTRAINT FK_TBL_LETTER FOREIGN KEY (WORD_ID) REFERENCES TBL_WORD (WORD_ID),
CONSTRAINT FK_TBL_LETTER FOREIGN KEY (LETTER_ID) REFERENCES TBL_REF_LETTER (LETTER_ID)
)

