USE KiMeTzion
GO

DROP TABLE IF EXISTS TBL_NIKKUD;

SET NOCOUNT ON; 

CREATE TABLE TBL_NIKKUD
(
NIKKUD_LETTER_ID INT NOT NULL,
NIKKUD_ID INT NOT NULL,
CONSTRAINT FK_TBL_NIKKUD FOREIGN KEY (NIKKUD_LETTER) REFERENCES TBL_LETTER (ID),
CONSTRAINT FK_TBL_NIKKUD FOREIGN KEY (NIKKUD_ID) REFERENCES TBL_REF_NIKKUD (NIKKUD_ID)
)
