USE KiMeTzion
GO

DROP TABLE IF EXISTS TBL_TAAM_LETTER;

SET NOCOUNT ON; 

CREATE TABLE TBL_TAAM_LETTER
(
TAAM_LETTER_ID INT NOT NULL,
TAAM_ID INT NOT NULL,
CONSTRAINT FK_TBL_TAAM_LETTER FOREIGN KEY (TAAM_LETTER_ID) REFERENCES TBL_LETTER (ID),
CONSTRAINT FK_TBL_TAAM_LETTER FOREIGN KEY (TAAM_ID) REFERENCES TBL_REF_TAAM (TAAM_ID)
)