USE KiMeTzion;
​
DROP TABLE IF EXISTS TBL_NIKKUD_LETTER;
​
SET NOCOUNT ON; 
​
CREATE TABLE TBL_NIKKUD_LETTER
(
NIKKUD_LETTER_ID INT IDENTITY NOT NULL,
LETTER_ID INT NOT NULL,
NIKKUD_ID INT NOT NULL,
CONSTRAINT PK_TBL_NIKKUD_LETTER PRIMARY KEY (NIKKUD_LETTER_ID),
CONSTRAINT FK_TBL_NIKKUD_LETTER_LETTER_ID FOREIGN KEY (LETTER_ID) REFERENCES TBL_LETTER (LETTER_ID),
CONSTRAINT FK_TBL_NIKKUD_LETTER_NIKKUD_ID FOREIGN KEY (NIKKUD_ID) REFERENCES TBL_REF_NIKKUD (NIKKUD_ID)
)